require 'shellwords'
require_relative 'bbiff/version'
require_relative 'bbiff/bbs_reader'
require_relative 'bbiff/res_format'
require_relative 'bbiff/settings'
require_relative 'bbiff/executable'
require_relative 'bbiff/show'
